//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEC_PID_Control {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class MainSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainSettings defaultInstance = ((MainSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainSettings())));
        
        public static MainSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool K2400LogExpanded {
            get {
                return ((bool)(this["K2400LogExpanded"]));
            }
            set {
                this["K2400LogExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double K2400OutputVoltage {
            get {
                return ((double)(this["K2400OutputVoltage"]));
            }
            set {
                this["K2400OutputVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double K2400OutputCurrent {
            get {
                return ((double)(this["K2400OutputCurrent"]));
            }
            set {
                this["K2400OutputCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool K2400Expanded {
            get {
                return ((bool)(this["K2400Expanded"]));
            }
            set {
                this["K2400Expanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string K2400Port {
            get {
                return ((string)(this["K2400Port"]));
            }
            set {
                this["K2400Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GWPSLogExpanded {
            get {
                return ((bool)(this["GWPSLogExpanded"]));
            }
            set {
                this["GWPSLogExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double GWPSOutputVoltage {
            get {
                return ((double)(this["GWPSOutputVoltage"]));
            }
            set {
                this["GWPSOutputVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double GWPSOutputCurrent {
            get {
                return ((double)(this["GWPSOutputCurrent"]));
            }
            set {
                this["GWPSOutputCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GWPSExpanded {
            get {
                return ((bool)(this["GWPSExpanded"]));
            }
            set {
                this["GWPSExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string GWPSPort {
            get {
                return ((string)(this["GWPSPort"]));
            }
            set {
                this["GWPSPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current:uA")]
        public string K2400OCFormat {
            get {
                return ((string)(this["K2400OCFormat"]));
            }
            set {
                this["K2400OCFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Voltage:V")]
        public string K2400OVFormat {
            get {
                return ((string)(this["K2400OVFormat"]));
            }
            set {
                this["K2400OVFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current:uA")]
        public string K2400MCFormat {
            get {
                return ((string)(this["K2400MCFormat"]));
            }
            set {
                this["K2400MCFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Voltage:V")]
        public string K2400MVFormat {
            get {
                return ((string)(this["K2400MVFormat"]));
            }
            set {
                this["K2400MVFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current:uA")]
        public string GWPSOCFormat {
            get {
                return ((string)(this["GWPSOCFormat"]));
            }
            set {
                this["GWPSOCFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Voltage:V")]
        public string GWPSOVFormat {
            get {
                return ((string)(this["GWPSOVFormat"]));
            }
            set {
                this["GWPSOVFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current:uA")]
        public string GWPSMCFormat {
            get {
                return ((string)(this["GWPSMCFormat"]));
            }
            set {
                this["GWPSMCFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Voltage:V")]
        public string GWPSMVFormat {
            get {
                return ((string)(this["GWPSMVFormat"]));
            }
            set {
                this["GWPSMVFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resistance:kOhm")]
        public string K2400RFormat {
            get {
                return ((string)(this["K2400RFormat"]));
            }
            set {
                this["K2400RFormat"] = value;
            }
        }
    }
}
